Revert "haproxy ipblocks-all: Filter disabled ipblocks"
This reverts commit d96ab93bc8a3527fb80f0ce6284c769c2f3f0091.

Reason for revert:
ERROR template: _etc_haproxy_ipblocks.d_all.map.tmpl:4:11: executing
"_etc_haproxy_ipblocks.d_all.map.tmpl" at <ne $ipblock.enabled false>:
error calling ne: incompatible types for comparison

Change-Id: I6f9a0c1c2709d70eadd97aa8bca83891beeed748