hhvm: log dir creation requires rsyslog
The $log_dir resource needs a syslog user but might be released before
rsyslog is installed (via rsyslog::conf). That in turns cause:

Error: Could not set 'directory' on ensure: Could not find user syslog
at 285:/puppet/modules/hhvm/manifests/init.pp

Mark $log_dir as requiring rsyslog for the 'syslog' user.

Flip rsyslog::conf dependency on /etc/logrotate.d/hhvm which can be
realized after the rsyslog configuration.

Change-Id: I2ff82d6e3e1d9eadbc68a3e9c9a0fb535290b89b