aptrepo: add A278B781FE4B2BDA key to cassandra repo
Looks like the Apache Cassandra repository is now signed by this key:

ERROR: Condition '749D6EEC0353B12C' not fullfilled for '/srv/wikimedia/lists/cassandra_21x_InRelease'.
Signatures in '/srv/wikimedia/lists/cassandra_21x_InRelease':
'A278B781FE4B2BDA' (signed 2016-10-10): missing pubkey

$ gpg --recv-keys A278B781FE4B2BDA
gpg: requesting key FE4B2BDA from hkp server pool.sks-keyservers.net
gpg: key FE4B2BDA: public key "Michael Shuler <michael@pbandjelly.org>"
imported

See also related issue https://issues.apache.org/jira/browse/CASSANDRA-12239

Change-Id: I7ba3cb713fab2faee2e9eed699a417d6f9ba8cd4