graphite alerts, fix analytics monitoring group name
icinga config was broken because it was looking for a
contact group called "analytics_eqiad" which did not exist.

analytics_eqiad is a service group, but not a contact group.

the contact group is just called analytics.

Checking services...
Error: Contact group 'analytics_eqiad' specified in service 'Kafka MirrorMaker analytics-eqiad' for host 'kafka1001' is not defined anywhere!
Error: Contact group 'analytics_eqiad' specified in service 'Kafka MirrorMaker analytics-eqiad' for host 'kafka1002' is not defined anywhere!
	Checked 18872 services.

Change-Id: I8bd1ce9891389566f1f81d04e284035d7d4e55cd