Revert "Bounce keyholder-proxy when keyholder-auth.d group -> key..."
This reverts commit c70d360a8a2dacf10bcede0ab65cfb51be7b736c.

Reason for revert: Broke puppet:

Error: Found 1 dependency cycle:
(Exec[systemd daemon-reload for keyholder-proxy.service (keyholder-proxy)] => 
  Service[keyholder-proxy] => Systemd::Service[keyholder-proxy] => Class[Keyholder] => 
  Keyholder::Agent[mwdeploy] => File[/etc/keyholder-auth.d/mwdeploy.yml] => 
  Systemd::Service[keyholder-proxy] => Service[keyholder-proxy])\nTry the '--graph' 
  option and opening the resulting '.dot' file in OmniGraffle or GraphViz
Error: Failed to apply catalog: One or more resource dependency 
cycles detected in graph

Let's just forget it! :)

Change-Id: I98128e9eded91c1f3ed826380015d4ff03993687