cross-validate-accounts: Don't crash when splitting an SSH key fails.
This failed due to a key missing the 'ssh-rsa' prefix:

  Traceback (most recent call last):
    File "/usr/local/bin/cross-validate-accounts", line 351, in <module>
      main()
    File "/usr/local/bin/cross-validate-accounts", line 347, in main
      run_test(check_ssh_keys(yamldata))
    File "/usr/local/bin/cross-validate-accounts", line 273, in check_ssh_keys
      production_key = i.split()[1]
  IndexError: list index out of range

The key was corrected in I4ee09819155edf4bfe8fa5d8d1fd987af7f2a3ac but
let's give the script a more useful error output in that case.

Change-Id: I28f6f93b0e1a3bb44215b57f03660525c45e3640