openstack: cinder.conf: specify lock path
Required by oslo:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cinder/backup/manager.py", line 146, in init_host
    self._cleanup_incomplete_backup_operations(ctxt)
  File "/usr/lib/python3/dist-packages/oslo_concurrency/lockutils.py", line 353, in inner
    fair=fair):
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/lib/python3/dist-packages/oslo_concurrency/lockutils.py", line 269, in lock
    ext_lock = external_lock(name, lock_file_prefix, lock_path)
  File "/usr/lib/python3/dist-packages/oslo_concurrency/lockutils.py", line 189, in external_lock
    lock_file_path = _get_lock_path(name, lock_file_prefix, lock_path)
  File "/usr/lib/python3/dist-packages/oslo_concurrency/lockutils.py", line 183, in _get_lock_path
    raise cfg.RequiredOptError('lock_path')
oslo_config.cfg.RequiredOptError: value required for option lock_path in group [DEFAULT]

Bug: T292546
Signed-off-by: Arturo Borrero Gonzalez <aborrero@wikimedia.org>
Change-Id: I25c88990e51757ad9503c76e5c6c5f464b623653