Create /etc/spicerack/elasticsearch/
Since the merge of 768816 Puppet is failing on the cumin hosts:

Error: Could not set 'present' on ensure: No such file or directory - A directory
component in /etc/spicerack/elasticsearch/config.yaml20220309-256514-1p17b8z.lock
does not exist or is a dangling symbolic link (file:
/etc/puppet/modules/profile/manifests/spicerack.pp, line: 189)

We need to create /etc/spicerack/elasticsearch/ in Puppet as well.

Hosts: cumin2002.codfw.wmnet
Change-Id: I368f2acca2383d909de3d8e5bc8dece6050f21b5