define ishmael_config() parameters lacked dollar signs
`puppet parser validate` is giving me errors on ishmael_config since
its parameter names are lacking dollars.

I.e:

 Error: Could not parse for environment production:
 Syntax error at 'db_central_host'; expected ')'
 at manifests/misc/ishmael.pp:22

Change-Id: If563ec2f7bd6383b8c52cb3d3541458bed6f5f8b