Adapt transition code for ferm -> nftables
- We need to purge the 'ferm' package, otherwise the init script and
  /etc/ferm/ferm.conf (which are both conffiles) remain, which makes
  the Puppet-driven removal of /etc/ferm fail
- We can only set the alternative if iptables is present, the removal
  of iptables also drops the alternatives config:

  Notice: /Stage[main]/Ferm/Alternatives::Select[iptables]/Exec
    [update_alternative_iptables]/returns: update-alternatives: error:
    no alternatives for iptables
  Error: '/usr/bin/update-alternatives --force --set iptables
    /usr/sbin/iptables-legacy' returned 2 instead of one of [0]
  Error: /Stage[main]/Ferm/Alternatives::Select[iptables]/
    Exec[update_alternative_iptables]/returns: change from 'notrun'
    to ['0'] failed: '/usr/bin/update-alternatives --force --set
    iptables /usr/sbin/iptables-legacy' returned 2 instead of one
    of [0] (corrective)

Bug: T336497
Hosts: C:profile::firewall
Change-Id: Ib936484704db989e93d7a794011459d84253cb0c