revert the SSL chain file  change on gerrit
change 84901 was ok for the other hosts, but on gerrit,
when not specifying the SSLCACertificatePath and then trying
puppet merge on sockpuppet you get:

error: server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt
CRLfile: none while accessing https://gerrit.wikimedia.org/r/p/operations/pus
fatal: HTTP request failed

so reverting it for now because it's Friday afternoon

Change-Id: I6955d613367f995855c36ef5d1acf386d9ff7489