openstack: fix not found responses
Fixes errors like this causing empty response bodies:

  File "/usr/local/lib/python3.9/dist-packages/puppet-enc.py", line 393, in delete_prefix
    prefix_id = cur.fetchone()[0]
  TypeError: 'NoneType' object is not subscriptable

Change-Id: Ieba88cba7b6e6e024686c2cecb1c214e34527c27