cloudbackup: fix disk allocation
The disk for LVM has 20GB, but something prevents us from using it all:

  Error: Execution of '/usr/sbin/lvcreate -n cinder-backups --size 20GB backup' returned 5:
    Volume group "backup" has insufficient free space (5119 extents): 5120 required.

Reduce the allocation by 1GB and see if then the math is right.

Bug: T295584
Signed-off-by: Arturo Borrero Gonzalez <aborrero@wikimedia.org>
Change-Id: I234d7714839a22b5c55b849eea9ee88d4c3c2633