Update Grafana package source
reprepro updates were failing with the error

 ERROR: Condition '37BBEE3F7AD95B3F' not fulfilled for
 '/srv/wikimedia/lists/grafana-stretch_stretch_InRelease'.
 Signatures in '/srv/wikimedia/lists/grafana-stretch_stretch_InRelease':
 '40F370A1F9081B64' (signed 2019-01-07): missing pubkey
 Error: Not enough signatures found for remote repository grafana-stretch
 (https://packagecloud.io/grafana/stable/debian stretch)!

Turns out that they moved the repository:
https://grafana.com/blog/2019/01/05/moving-to-packages.grafana.com/

Change-Id: Iae9e8b1f60bf69e40606fdebb37da07f638c35d7