Revert "jenkins: Adjust CSP header to allow inline CSS and video playback"
Breaks Jenkins:

  Error: Could not find or load main class default-src

This reverts commit 9170b1d5478873c05abfc9d17444647b8b985853.

Bug: T245658
Bug: T215115
Change-Id: I9246fd07e0b0ada43c5b54341f96cd97bded3212