ishmael - use apache::site
use the newer apache::site method
to setup Apache site instead of a file resource
and have proper symlinks again

current sitation is:

neon:/etc/apache2/sites-enabled# file ishmael.wikimedia.org
ishmael.wikimedia.org: ASCII text, with very long lines

neon:/etc/apache2/sites-available# file ishmael.wikimedia.org
ERROR: cannot open `ishmael.wikimedia.org' (No such file or directory)

due to refactoring

Change-Id: Iaf5879d55cde0ba87b718f6e340acf895fce5265