Openstack Glance: fix init-script to be ipv4 only
This tried to define a general ipv6/ipv4 listening port but that
causes confusion later on in oslo:

ValueError: Invalid IPv6 URL

Clearly something is confusing incoming ipv4 requests for ipv6
requests and then failing to parse. Setting us to 0.0.0.0
gets things past that problem.

Bug: T261136
Change-Id: I3c92bc14c51dcb45bc735c2e314f77546056d235