Revert "Set up scap target for deploying the phatality plugin into kibana"
I thought the patch was good to go, but it isn't in the sense that e.g.
the repository is empty. Also puppet fails:

Error: Could not retrieve catalog from remote server: Error 500 on
SERVER: Server Error: Invalid relationship:
Scap::Target[releng/phatality] { require => File[/srv/deployment] },
because File[/srv/deployment] doesn't seem to be in the catalog

This reverts commit 07e2aecb13c7e2288ade41e46cf258f73475098b.

Change-Id: I54577597b96e84eb311885e463db998c2a29fdcd