Openstack Trove: Hack in a bugfix that's missing from the debian package
Without this patch the guest agents can't talk to Trove; they fail
with

  Exception during message handling: AttributeError: 'TroveContext'
  object has no attribute 'notification'

Bug: T212595
Change-Id: I08c2dc492e3f67313f3a4debc32739ae2ad4bdb9