Revert "facilities: add codfw PDUs"
This change is making einsteinium/tegmen fail their puppet runs:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to submit 'replace catalog' command for einsteinium.wikimedia.org to PuppetDB at nitrogen.eqiad.wmnet:443: [413 Request Entity Too Large] <html><head><title>413 Request Entity Too Large</title></head><body bgcolor="white"><center><h1>413 Request Entity Too Large</h1></center><hr><center>nginx/1.11.3</center></body></html>
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

This reverts commit a8ae74c26aed0d45c43fcaa2c9adeb718854bce6.

Change-Id: I3eafb0868d61541991528bbe607c2ed087acd945