ci: add buildx on production Jenkins agents
As an aftermath of us having moved the Jenkins hosts to a new Debian
version (T431582), buildx is not available resulting in PipelineLib jobs
on the production agents to fail with:

  ERROR: BuildKit is enabled but the buildx component is missing or
         broken.
         Install the buildx component to build images with BuildKit:
         https://docs.docker.com/go/buildx/

Previously we used the Docker packages from upstream, we are now using
the one from Debian which does not come with Buildx by default, it is
shipped (since Trixie) as another package `docker-buildx`. See bug
https://bugs.debian.org/989917 ITP: docker-buildx.

The WMCS agents are using Bookworm docker-io which apparently has buildx
available.
The production agents (contint1003/contint2003) are using Trixie.

Install the missing `docker-buildx` package on Trixie agents.

Bug: T431582
Change-Id: I4c0dc4ae0d42d9de292d5e8ee592bce7f29e67bd