site.pp: fix lint errors/warns (puppet-lint 1.1)
Upgraded to puppet-lint 1.1.0-1 and after our recent
changes in Jenkins and our desire to make puppet-lint-lenient voting,
rechecked site.pp and fixing some that i found.

WARNING: double quoted string containing no variables on line 373
WARNING: double quoted string containing no variables on line 498
ERROR: two-space soft tabs not used on line 1778
WARNING: indentation of => is not properly aligned on line 916
WARNING: indentation of => is not properly aligned on line 917
WARNING: indentation of => is not properly aligned on line 929
WARNING: indentation of => is not properly aligned on line 930

This leaves a bunch of "more than 80 chars" and case statements
without a default. (with the current settings)

Change-Id: Ic8cae6ff40ecf9395a08d65c1f0e7ad768cf5fd2