Revert "Ensure that phabricator/src/extensions exists"
This reverts commit 4242b2fa038af7454c8f99a213c07158b0c3dcf8.

Error: Failed to apply catalog: Parameter require failed on
File[/srv/phab/phabricator/src/extensions/MediaWikiUserpageCustomField.php]:
No title provided and "/srv/phab/phabricator/src/extensions/"
is not a valid resource reference at
/etc/puppet/modules/phabricator/manifests/extension.pp:13
Wrapped exception:
No title provided and "/srv/phab/phabricator/src/extensions/" is not a valid resource reference

Change-Id: Iafe9d8039161c8ab2d62f9f7023a5c6443701fbe