Revert "scap: Port mwgrep to Python 3 and other cleanup"
This reverts commit 3682cff807e8509be1fcbdd8eabf9a9d85257d8f.

Traceback (most recent call last):
  File "/usr/local/bin/mwgrep", line 170, in <module>
    all_indices = local_indices + remote_indices
TypeError: unsupported operand type(s) for +: 'map' and 'list'

Change-Id: Ibe57811ea65ae996157835f161dc78142514be01