icinga - fix syntax error for check_ssl_ldap
follow-up to I52c19555706fe85b

fix syntax error in icinga config due to missing
! character leading to stuff like:

Error: Service check command 'check_ssl_ldaplabcontrol2001.wikimedia.org' specified
... not defined anywhere

Change-Id: I472d93de59585c71d8861c0a0482ef476bbe425b