gerrit: unmask gerrit.service on gerrit2003
the topology-check cookbook validates that the replica has the -replica
flag and has a valid and running systemd unit.

```
RuntimeError: Topology validation failed with the following issues:
- gerrit.service is not active on gerrit2003.wikimedia.org
- Replica host is missing the 'replica' flag in systemd unit.
```

We disabled replication with 1237450

Replication, if it was trying to send things to gerrit1003, would be
dropped by the firewall:
```
arnaudb@gerrit2003:~ $ sudo nmap -Pn -p 22,29418 gerrit1003.wikimedia.org
[...]
PORT      STATE    SERVICE
22/tcp    filtered ssh
29418/tcp open     unknown
```

gerrit2003 should identify itself as replica anyway (c.f. https://w.wiki/Hp5A)

Hosts: gerrit1003.wikimedia.org,gerrit2003.wikimedia.org
Bug: T387833
Change-Id: I72c36db2633e3c101055087a546b21b853a1a4b8