Revert "labs - hiera: migrate to hiera version5"
This reverts commit 466795ea5f524ac31c4670dc474c44f444a03983.

Reason for revert: 

puppetmaster-01.cloudinfra-codfw1dev.codfw1dev.wikimedia.cloud

Change-Id: Id350e6cc4f144849cb299e0b2ce3a0da4c8fd3de
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, undefined method `load_typed' for nil:NilClass (file: /etc/puppet/manifests/realm.pp, line: 68, column: 18) on node puppetmaster-01.cloudinfra-codfw1dev.codfw1dev.wikimedia.cloud