Add dfs.http.policy: 'HTTPS_ONLY' to the Hadoop test cluster
The option is needed to allow the datanode to properly bootstrap:
java.lang.RuntimeException: Cannot start secure DataNode without configuring
either privileged resources or SASL RPC data transfer protection and SSL for HTTP.
Using privileged resources in combination with SASL RPC data transfer
protection is not supported.

Bug: T217412
Change-Id: I7aa552bdc041f7f00adf61db0b7232a4d7248461