mailman: fix I/O monitoring on virtual machine
On sodium we did not have to specify a device name,
on fermium we have to, because it's /dev/vda, or:

ERROR: Device incorrectly specified

Let's try and use "is_virtual" here to know if we
are on a VM or not and then set the device to be checked
based on that.

https://docs.puppetlabs.com/facter/1.6/core_facts.html#isvirtual

---

notify{"am i virtual? $is_virtual - device: $iostat_device": }

fermium:/Main/Notify[am i virtual? true - device: vda]
sodium: /Stage[main]//Notify[am i virtual? false - device: sda]

Bug:T109925
Change-Id: I6c453046b00ca1b12db354f1bcd938d01029948c