hhvm: vary /var/log/hhvm owner based on distro
On Ubuntu syslog runs as the user 'syslog' but on Debian rsyslog runs as
root and the package does not provide any 'syslog' user.

Applying the ::hhvm class on Jessie yields:

Error: Could not set 'directory' on ensure:
  Could not find user syslog
  at 285:/puppet/modules/hhvm/manifests/init.pp

Vary the directory owner based on the distribution. 'syslog' per default
and for Ubuntu, but 'root' for Debian.

Change-Id: Ia2ee6d493a5321ca56521dc64a24423903746918