static_tendril: use wmflib::dir::mkdir_p to ensure docroot exists
follow-up to I8f61053bfe16fb

Use our own mkdir_p to ensure the docroot exists before files
in it are created.

To fix:

Error: /Stage[main]/Profile::Microsites::Static_tendril/File
[/srv/org/wikimedia/static-tendril/index.html]/ensure:
change from 'absent' to 'file' failed:
Could not set 'file' on ensure: No such file or directory
A directory component ... does not exist or is a dangling symbolic link.

file: /etc/puppet/modules/profile/manifests/microsites/static_tendril.pp, line: 8

Bug: T297605
Change-Id: I6aaf7cc247be46d7a38f4a3763e79196d8759437