python::venv: Create deploy-foo user using systemd::sysuser
This currently fails on cumin1001 with

Error: Could not create user deploy-homer: Execution of '/usr/sbin/useradd -g
deploy-homer -s /bin/bash -M -r deploy-homer' returned 6: useradd:
group 'deploy-homer' does not exist

Simply use systemd::sysuser which does the right thing.

Hosts: cumin2002.codfw.wmnet
Change-Id: I197ceaa8d6f4c501276d711dc753725bbd2f6057