prometheus: fix "Configure prometheus metrics on the cephosd cluster"
This fixes commit e9ccdf41b4a7e8f0aa736ece1a8378d977e4cec0.

Reason for fix: This change breaks puppet on prometheus nodes
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation
Error: Error while evaluating a Resource Statement, Duplicate declaration:
Prometheus::Class_config[ceph_codfw] is already declared at (file:
/srv/puppet_code/environments/production/modules/profile/manifests/prometheus/analytics.pp, line:
120); cannot redeclare (file:
/srv/puppet_code/environments/production/modules/profile/manifests/prometheus/cloud.pp, line: 248)
(file: /srv/puppet_code/environments/production/modules/profile/manifests/prometheus/cloud.pp,
line: 248, column: 5) on node prometheus2005.codfw.wmnet

Bug: T369583
Bug: T369582
Hosts: auto
Change-Id: I4d190dbd47fabf226ce3f26444ab9c335f2ec5ca