ores: disable new monitoring check
For some reason the virtual host does not get created.

Error: Could not find any host matching 'ores.wmflabs.org'

This is strange because we do _the exact same thing_ in other
places and it works just fine.

We need to look at this more but until then i don't want to
let icinga config be broken. It prevents any icinga reloads.

Change-Id: I04e09a0bf2fc94e938ca20aea8090cfed92a52fd