apifeatureusage: explicitly define java package version
Use `profile::java::java_packages` entry in hieradata,
and use the `openjdk-17-jdk` package instead of the headless
variant.

The hope is that this will quash the error:
```
Error: Could not retrieve catalog from remote server: Error 500 on
SERVER: Server Error: Could not find resource
'Package[openjdk-17-jdk-headless]' in parameter 'require' (file:
/srv/puppet_code/environments/production/modules/logstash/manifests/
init.pp, line: 51) on node apifeatureusage2001.codfw.wmnet
```

Hosts: apifeatureusage2001.codfw.wmnet
Bug: T433890
Change-Id: If021d61a34621e41564e5df7fc59e655d8125368