Revert "install fonts-wqy-zenhei on app servers"
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install fonts-wqy-zenhei' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
Package fonts-wqy-zenhei is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'fonts-wqy-zenhei' has no installation candidate

Error: /Stage[main]/Mediawiki::Packages::Fonts/Package[fonts-wqy-zenhei]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install fonts-wqy-zenhei' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
Package fonts-wqy-zenhei is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'fonts-wqy-zenhei' has no installation candidate

This reverts commit a3bb810d6be17045ff9cf4f5ed8face8e1b69abf.

Change-Id: I3cad5e64aa4c586935763610cf50f1a86370fae2