Revert "swift: refactor into module, add codfw"
makes puppet fail everywhere in codfw:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER:
Error from DataBinding 'hiera' while looking up 'admin::always_groups': syntax
error on line 88, col 1: `]' on node ms-be2001.codfw.wmnet

This reverts commit 758a6f81594e97b6592249bda10698a49602d6f3.

Change-Id: If0ba7cfd73857245a4063b69a55fc2431a3a01a0