gerrit: fix dependency cycle Letsencrypt/Apache
The require was added to letsencrypt::cert::integrated
in I393a1775e9e7 but causes this cycle:

Error: Could not apply complete catalog: Found 1 dependency cycle:

(Exec[acme-setup-acme-gerrit] => Letsencrypt::Cert::Integrated[gerrit]
=> Apache::Site[gerrit.wikimedia.org] => Apache::Conf[gerrit.wikimedia.org]
=> File[/etc/apache2/sites-available/50-gerrit-wikimedia-org.conf]
=> Service[apache2] => Exec[acme-setup-acme-gerrit])

Change-Id: Ib790c40f48cbaf7b00da9d928147cd6242f19589