Revert "graphite: add graphite1004 to cluster_servers"
This reverts commit 5072a5ac7121996d2c8bc554b21c24c1d709e9b3.

Reason for revert: Errors in graphite web interface

  File "/usr/lib/python2.7/dist-packages/graphite/remote_storage.py", line 90, in get_results
    resultNodes = [ RemoteNode(self.store, node['metric_path'], node['isLeaf']) for node in results ]
KeyError: 'metric_path'

Change-Id: I3654cc5b0adf8d0d906f11e7a87cb8e63562f786