include GlobalSign CA cert on neon for monitoring
icinga needs to have the (intermediate) CA cert to be
able to run check_cert for monitoring of certificates

we use check_cert here which takes exactly 3 args and
the last is the CA cert

usage("check_cert <hostname> <port> <CAfile>..
from files/icinga/check_cert

if we don't install this here we get these:

SSL error: [Errno 1] _ssl.c:504: error:14090086:SSL  ..

causing false positives like on:

https://icinga.wikimedia.org/cgi-bin/icinga/extinfo.cgi?type=2&host=labcontrol2001&service=Certificate+expiration

Change-Id: Icf161e2fc1e7e0bce2583cd22fa8301c7c52487a