cinderutils: add --allow-unattended-format when preparing volumes
I tried to use this code at Id2f6a8309272 and puppet tried to run
the wmcs-prepare-cinder-volume command but that failed with:

Error: '/usr/local/sbin/wmcs-prepare-cinder-volume --force
        --device sdb --mountpoint /srv/wikistats/backup
        --options discard,nofail,x-systemd.device-timeout=2s
        --mountmode 755' returned 1 instead of one of [0]'


When I manually ran the same full command that puppet runs I got:

"Refusing to format volume in non-interactive mode without
--allow-unattended-format""

Only after dropping the --force option I could manually run it
but then it's interactive and asks the user for input.

Bug: T371573
Change-Id: Ie8b536557b9b434f8d79300ea99f0c387d0cdf95