toolforge: elasticsearch: nginx: fix dependency cycle
Prevent this puppet dependency cyle:

Error: Failed to apply catalog: Found 1 dependency cycle:
(File[/etc/nginx/elasticsearch.htpasswd] =>
  Service[nginx] =>
    Class[Nginx] =>
      File[/etc/nginx/elasticsearch.htpasswd])

We only really need the /etc/nginx directory which is deployed by the
nginx-common package.


Bug: T236606
Change-Id: I01f151a0324bd367eefb6b5ca747deca0a9e4fd8
Signed-off-by: Arturo Borrero Gonzalez <aborrero@wikimedia.org>