puppet-tests: remove broken inclusion of nagios.pp
The file manifests/nagios.pp has been moved in I21a3ca32fd425dd20
and does not exist anymore in this place.

When trying to compile changes to the tests files itself you get:

Error: No file(s) found for import of '../../../manifests/nagios.pp'
like on https://integration.wikimedia.org/ci/job/pplint-HEAD/10231/console

Change-Id: I6b5279947b24c63e10d0b66974bb3b23c57d46e8