hhvm: add missing " in hhvm.default.systemd.erb
This popped up as " /etc/init.d/hhvm: 10: /etc/default/hhvm: Syntax
error: Unterminated quoted string" on mw1201 (and others).

Since this file was last edited back in April i am really surprised
though it did not show up earlier.

Change-Id: I0e14f3509c3ed5ac44adfbad101efc8abe553acb