Fix: the backend argument is required in our cryptography version
We were seeing this error in production:

```
Traceback (most recent call last):
  File "/usr/local/bin/prometheus-check-certificate-expiry", line 56, in <module>
    sys.exit(main())
  File "/usr/local/bin/prometheus-check-certificate-expiry", line 40, in main
    cert = x509.load_pem_x509_certificate(certificate_content)
TypeError: load_pem_x509_certificate() missing 1 required positional argument: 'backend'
```
due to the fact that many of our nodes run Buster, which includes a
cryptography version in which `backend` is required.

Change-Id: Id31678a5fe65e4c2541f7f0a587bbc12428fb595