Revert "systemd::timer::job: add typing for $interval"
This reverts commit 788bd015a46a75c4cce36adcb0bb1d979eec808a.

Reason for revert:
krenair@deployment-deploy01:~$ puppet --version
4.8.2

Change-Id: I14df657ff5265f0c5002798bf8500fdf1fe4223e
Error: Error while evaluating a Type-Name, Attempt to redefine entity 'http://puppet.com/2016.1/runtime/type/systemd::timer::schedule'. Originally set /etc/puppet/modules/systemd/types/timer/schedule.pp. at /etc/puppet/modules/systemd/manifests/timer/job.pp:87:5