swift: use resurce for swiftrepl tidy
Causes apply failure otherwise:

Error: Failed to apply catalog: Parameter matches failed on
Tidy[/var/log/swiftrepl]: Tidy can't use matches with recurse 0, false,
or undef (file: /etc/puppet/modules/swift/manifests/swiftrepl.pp, line:
33)

Bug: T162123
Change-Id: Idf68f438744e7b5cd3cd1b7196852fccba936755