planet: fix updates of UK planet, replace non-ASCII chars
The update of the uk.planet has been failing due to:

UnicodeEncodeError: 'ascii' codec can't encode characters...

When I65edfd46454c5 replaced planet update crons with systemd
timers it became obvious because the service for uk failed which
triggers Icinga systemd state alerting.

Replacing the non-ASCII chars should fix it.

Change-Id: Ie0b25d4417548ad972b595172e043a80294ecbf5