gerrit: make sure to not drop empty sets
The initial patch If03d531b0f6816d88eb1f10d3b2ac2b394502b37 creates to
drop rules for ipv4 and ipv6. If one of those sets is empty, nftables
fails with:

Error: Statement after terminal statement has no effect

So this change adds two more ensure parameters which reflect empty
ipv4 and ipv6 sets.

Bug: T348734
Bug: T351817
Change-Id: I1c1e4e99577e76622fda23964a787646f043fb26