graphite::wmcs::archiver: fix daily cronspam
What:
Attempt to fix daily cronspam to root@ from cloudmetrics100[1,2].

Why:
There are two emails that we get daily:

Traceback (most recent call last):
  File "/usr/local/bin/archive-instances", line 22, in <module>
    import yaml
ImportError: No module named yaml

/usr/lib/python2.7/dist-packages/keystoneauth1/adapter.py:200:
UserWarning: Using keystoneclient sessions has been deprecated.
             Please update your software to use
             keystoneauth1.warnings.warn(
               'Using keystoneclient sessions has been deprecated. '

Change-Id: I72eceb1bf655a578a47006ce5ac5d9eed2af5cd3