Disable the gmond apache_status module on ceph hosts
gmond stopped working on the two aggregators for the ceph cluster,
causing the whole cluster to show as "down" in the web frontend.
The log from gmond -d3 says:

[PYTHON] Can't call the metric handler function for [ap_idle_workers] in the python module [apache_status].
Traceback (most recent call last):
  File "/usr/lib/ganglia/python_modules/apache_status.py", line 122, in get_value
    metrics = get_metrics()[0]
...
socket.error: [Errno 104] Connection reset by peer

And disabling the module manually appears to fix the problem. No issue
observed on the main appservers, but they use the prefork MPM, not the
worker MPM.

Also fix the cluster name in gmetad.conf.

Change-Id: Ie1f9bc3355a3f6016b67f65b8be0c5827645b3e7