thumbor: require only instance_service_path
Causes a catalog compilation failure:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER:
Invalid relationship: Service[thumbor@8801] { require =>
File[/srv/thumbor/tmp/thumbor@8801] }, because
File[/srv/thumbor/tmp/thumbor@8801] doesn't seem to be in the catalog
Warning: Not using cache on failed catalog

Also the related exec has before => Service already.

Change-Id: Iecd51b7b11dca8fb3303039e91166937801543dc