sslcert: add text=True to Popen for update-ocsp.py
The update-ocsp-all script is returning the following exception:

k, v = cert_x509_option(filename, attrib).split("=", 1)
TypeError: a bytes-like object is required, not 'str'

As far as I can see cert_x509_option calls check_output_errtext,
that calls Popen's communicate, that in turns returns a bytearray
string.

Bug: T321309
Change-Id: I973a1b598648b150c0696e0e1b391608d406672c