mariadb: Fix host db2130 removed from puppet by mistake
Followup to 34cdd226a6c806777584b138dfc5ce8a3fcc0b6a

db2130 was mistakenly removed from production, mixed with db1130.
Hiera config seems to be right.

This should solve alert:

WARNING: Failed to apply catalog, zero resources tracked by Puppet.
Could be an interrupted request or a dependency cycle.

And puppet error:

Error: Could not retrieve catalog from remote server:
Error 500 on SERVER: Server Error: Evaluation Error:
Error while evaluating a Function Call,
No puppet role has been assigned to this node.
(file: /etc/puppet/manifests/site.pp, line: 2869, column: 9)
on node db2130.codfw.wmnet
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
No puppet role has been assigned to this node

Change-Id: Iec5cc1d973c913bf3b245427c70b33073341e64a