This is broken:
Error: Service check command 'check_procs_mailman' specified in service 'mailman' for host 'sodium' not defined anywhere!
Error: Service check command 'check_procs_spamd' specified in service 'spamassassin' for host 'sodium' not defined anywhere!

Please fix and resubmit.

This reverts commit c0ab10c1dcc39d64a88a3896cb7b64dea47b9fe8