phabricator: ensure /srv/dumps exists
This directory wasn't puppetized and must have been
manually created on iridium or something.

It exists there but not on phab1001, and i noticed
because there was cron spam to root from
 /srv/phab/tools/public_task_dump.py which said:

IOError: [Errno 2] No such file or directory:
'/srv/dumps/phabricator_public.dump'

when trying to write a dump.

Bug: T163938
Change-Id: I3247552f49d4e1e6d67ae78312d1f47e47ff0c96