work around puppet function arity issues
passing an explicit array to a function will change the function arity, thus
making require_package fail:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER:
undefined method `tr' for ["graphite-carbon", "python-whisper"]:Array at
/etc/puppet/modules/graphite/manifests/init.pp:17 on node tungsten.eqiad.wmnet
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Change-Id: I89ca6edae9764f36303860a980ae15d56fc77c55