Revert "puppet/self: use the appropriate override"
Causes puppet error on labs puppetmaster self:

Error: Could not retrieve catalog from remote server:
  Error 400 on SERVER: Only subclasses can override parameters
  at 79:modules/puppet/manifests/self/config.pp

This reverts commit 103148552dedf75ee371683801b95b3056032841.

Bug: T102947
Change-Id: I7d842def6ebd3d625f1260fa0a5ba881f0365805