wikitech-static monitoring, ? is illegal character
Using a "?" in the service description wasn't a good idea. It caused Icinga
config breakage.

Error: The description string for service 'are wikitech and wt-static in sync?'
on host 'silver' contains one or more illegal characters.

Bug:T89323
Change-Id: I23d89fde5e60a0b79a86f5b45c767f3368e5cc94