foreachwikiindblist: Return early when no arg is passed
instead of crashing like:

Notice: Undefined offset: 0 in /srv/mediawiki/multiversion/MWWikiversions.php on line 71
Fatal error: Uncaught Exception: MWWikiversions::readDbListFile: unable
to read . in /srv/mediawiki/multiversion/MWWikiversions.php:98
Stack trace:
  thrown in /srv/mediawiki/multiversion/MWWikiversions.php on line 98

Change-Id: Ia0fab70f90f622e3bb293d1277ead0b623212bc9