racktables: notify apache2 Service
notifying the class introduces a dependency cycle:

Error: Could not apply complete catalog: Found 1 dependency cycle:
(Exec[ensure_present_mod_php5] => Apache::Mod_conf[php5] =>
Class[Apache::Mod::Php5] => File_line[racktables_php_memory] => Class[Apache]
=> Package[apache2] => Exec[ensure_present_mod_php5])

Bug: T102092
Change-Id: Ic927a45be5d7b13b5107a959b2aa3a0cd2bcbb42