aptrepo: add A278B781FE4B2BDA key to cassandra repo
Looks like the Apache Cassandra repository is now signed by this key:

ERROR: Condition '749D6EEC0353B12C' not fullfilled for '/srv/wikimedia/lists/cassandra_21x_InRelease'.
Signatures in '/srv/wikimedia/lists/cassandra_21x_InRelease':
'A278B781FE4B2BDA' (signed 2016-10-10): missing pubkey

Change-Id: I7ba3cb713fab2faee2e9eed699a417d6f9ba8cd4