Turn off sshd MAC and KEX hardening for gerrit replication targets
Gerrit's replication plugin failed to negotiate the used algorithm on
machines that used the hardened sshd MAC and KEX setup and filled logs
with

  [2015-05-21 15:47:41,273] ERROR com.googlesource.gerrit.plugins.replication.ReplicationQueue : Cannot replicate to gerritslave@gallium.wikimedia.org:/srv/ssd/gerrit/mediawiki/extensions/ConfirmEdit.git
  org.eclipse.jgit.errors.TransportException: gerritslave@gallium.wikimedia.org:/srv/ssd/gerrit/mediawiki/extensions/ConfirmEdit.git: Algorithm negotiation fail

Hence, we now turn off those hardenings for gerrit replication
targets, to allow gerrit to replicate again.

Bug: T99990
Change-Id: I08d0a64d1902f161c66bd3ad80b8e85df5657e48