diamond: fix up dependencies
Should resolve

Error: /.../Diamond::Collector[..]/File[/usr/share/diamond/collectors/SSHSessions]/ensure:
    change from absent to directory failed: Cannot create
    /usr/share/diamond/collectors/SSHSessions; parent directory
    /usr/share/diamond/collectors does not exist

and further dependencies.

Change-Id: I5769e347c6c3b407430147982c3db1dd40e1e003