contint: Remove ruby2.1 as it is in base package
Because base will install it anyways, ruby2.1 conflicts as then it is set in both places

Change-Id: I9ee4c6d39e4d94dedb79716599731e83ff488148
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Package[ruby2.1] is already declared in file /etc/puppet/modules/base/manifests/standard_packages.pp:119; cannot redeclare at /etc/puppet/modules/contint/manifests/packages/ruby.pp:26 on node jenkins-slave-01.git.eqiad.wmflabs
Warning: Not using cache on failed catalog