toollabs: remove redis Sysctl[vm.overcommit_memory]
which is already present in the Redis role, and thus causes

    Error: Could not retrieve catalog from remote server:
    Error 400 on SERVER: Duplicate declaration:
    Sysctl::Parameters[vm.overcommit_memory] is already
    declared in file
    /etc/puppet/modules/toollabs/manifests/redis.pp:39;
    cannot redeclare at
    /etc/puppet/modules/redis/manifests/init.pp:56 on node
    tools-redis-01.tools.eqiad.wmflabs

Change-Id: I77a15962944a42e771f22defde2321e9884c0015
Related-Change-Id: I81d749a81399fef8caa05301909dea8ab21ee51c