Use newer guava jar in druid hdfs cdh storage extension
The guava jar that cdh uses caused an error for larger jobs in Druid 0.9.2 hadoop indexing tasks:

2017-08-03T18:01:09,897 ERROR [main] org.apache.hadoop.mapred.YarnChild - Error running child : java.lang.NoSuchMethodError: com.google.common.io.Files.asByteSink(Ljava/io/File;[Lcom/google/common/io/FileWriteMode;)Lcom/google/common/io/ByteSink;
	at io.druid.segment.IndexMerger.makeIndexFiles(IndexMerger.java:801)
	at io.druid.segment.IndexMerger.merge(IndexMerger.java:438)
	at io.druid.segment.IndexMerger.persist(IndexMerger.java:186)
	at io.druid.indexer.IndexGeneratorJob$IndexGeneratorReducer.persist(IndexGeneratorJob.java:510)
	at io.druid.indexer.IndexGeneratorJob$IndexGeneratorReducer.reduce(IndexGeneratorJob.java:688)
	at io.druid.indexer.IndexGeneratorJob$IndexGeneratorReducer.reduce(IndexGeneratorJob.java:478)
	at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:171)
	at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:627)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:421)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

Bug: T170590
Change-Id: I2e7dcff24324e87dd1251a2131dea8c9e78ec1dc