modules/admin: drop gid field from ml-lab-users on lab machines
Without the gid: specified, the code uses the existing Debian posix
group by name. If we specify the GID but the group already exists, we
get:

```
Error: Could not set gid on group[render]: Execution of
'/usr/sbin/groupmod -g 842 render' returned 4: groupmod: GID '842'
already exists
Error:
/Stage[main]/Admin/Admin::Hashgroup[ml-lab-users]/Admin::Group[render]/Group[render]/gid:
change from 105 to 842 failed: Could not set gid on group[render]:
Execution of '/usr/sbin/groupmod -g 842 render' returned 4: groupmod:
GID '842' already exists
```

Bug: T376380
Change-Id: I1603377454ddc2c91fa3fa757348e3af4d671de5