Revert "wmcs: port ::instance to firewall::service"
This reverts commit 39aa3e2308e7bf0ccbf12757120229f5708afa8d.

Reason for revert: causes puppet failures on wmcs


Change-Id: Ia15d8c9037ccbc6c8332a5aa66c93298e7186248
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Class[Firewall] is already declared; cannot redeclare (file: /srv/puppet_code/environments/production/modules/profile/manifests/firewall.pp, line: 47) (file: /srv/puppet_code/environments/production/modules/profile/manifests/firewall.pp, line: 47, column: 5) on node tools-proxy-10.tools.eqiad1.wikimedia.cloud