aptrepo: add support for buster, install python-apt package
On buster using the apt_repo role:

ImportError: No module named apt_pkg

The python package is missing.

Bug: T224576
Change-Id: I0caa39eeefeb05226e6f5f07855138840e3d6db9