maps/icinga: add missing hostgroup maps-test-vectortiles_codfw
follow-up to I004790c3528cf4e3a5 which introduced an Icinga
config error:

Error: Could not find any hostgroup matching
'maps-test-vectortiles_codfw'

which kept Icinga from reloading config changes as reported
by Chase

Change-Id: If9a5e153d66b25c735e5b120aa6ed771be005ed3