mailman: fix I/O monitoring on fermium
On sodium we did not have to specify a device name,
on fermium we have to, because it's /dev/vda, or:

ERROR: Device incorrectly specified

Bug:T109925
Change-Id: I6c453046b00ca1b12db354f1bcd938d01029948c