Revert "Icinga: add check_bfd check (part 1)"
This reverts commit 78a66ec1a5b9bc62924fdcf66717477543ab6df3.

Error: python-snimpy : Depends: python-cffi-backend-api-9729


Change-Id: I4792eff19209da90898d1539b56a04d4d7c87440