hhvm: add missing " in hhvm.default.systemd.erb
This popped up as " /etc/init.d/hhvm: 10: /etc/default/hhvm: Syntax
error: Unterminated quoted string" on mw1201 (and others) when
trying to (re-)start hhvm. 

It meant that f.e. on mw1201 hhvm would not start when trying to
manually start it, then when adding the " it would start fine
and then puppet rebroke it.

Since this file was last edited back in April i am really surprised
though it did not show up earlier.

Change-Id: I0e14f3509c3ed5ac44adfbad101efc8abe553acb