dragonfly: Don't run pki::get_cert in ensure=absent case
With ensure == 'absent' get_cert fails because the user (owner) does not exist:
Error: Could not execute posix command: Invalid user: dragonfly

The user (and /etc/dragonfly) is created by the debian package which will not
be installed in case of ensure == 'absent'

Bug: T286054
Change-Id: I29a6e7374b1def1acc55c91ea07fbcc7cab578c4