diamond: collectors require python-diamond
Spotted while running puppet:

  Error: Cannot create
  /usr/share/diamond/collectors/MinimalPuppetAgent;
  parent directory /usr/share/diamond/collectors does not exist

The parent directory is not defined in puppet but is provided by the
package:

  $ dpkg -L python-diamond|grep /usr/share/diamond/collectors$
  /usr/share/diamond/collectors
  $

Change-Id: I94ad33233695b5e7dd3a63a251bdac8da6260858