graphite::wmcs::archiver: fix more errors in archive-instances
What:
Require two more packages to allow a proper run of the archive-instances
cron.

Why:
The following error is sent to root@ daily:
Traceback (most recent call last):
  File "/usr/local/bin/archive-instances", line 24, in <module>
    from keystoneclient.auth.identity.v3 import Password as KeystonePassword
ImportError: No module named keystoneclient.auth.identity.v3

Note: the archive-instances cron still sends emails to root@ daily due to
 UserWarning: Using keystoneclient sessions has been deprecated.
 Please update your software to use keystoneauth1.
 warnings.warn('Using keystoneclient sessions has been deprecated.

In my previous attempt I didn't consider that the error messages was sent
to stderr, so > /dev/null doesn't really work. To fix the problem I'd move
the crons to systemd timers or I'd just upgrade the archive-instances.py
code to avoid the warning (that seems legitimate).

Change-Id: I439bac57aaeefd8bc72aa698a59a9396ddc0417b