ganglia: set site in labs to eqiad to avoid error with ulsfo
Looks like "labsdnsconfig" is missing for ulsfo, causing:

$dnsconfig = hiera_hash('labsdnsconfig', {})
->
TypeError: Data retrieved from Ganglia is String not Hash

trying with eqiad

Change-Id: I9d1fdd90dea1f3f8d97280adeb8bb6d869fe5a4f