phabricator: solve dependency cycle for sysyser phd
follow-up to I7aeb1af5c966fbb0930f0ed4

Error: Found 1 dependency cycle:
(Exec[Refresh sysusers] => User[phd] => File[/var/run/phd]
=> Systemd::Sysuser[phd] => User[phd]

The User[phd] resource already requires the home dir,
leading to a dependency cycle if another require is added here.

Bug: T326146
Change-Id: I5f52dbf19c450232da11416ffb2ce1bd0b19d21e