Fix duplicate declaration of Package[python-designateclient]
Puppet runs on californium are failing with

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Package[python-designateclient] is already declared; cannot redeclare at /etc/puppet/modules/openstack/manifests/horizon/service.pp:21 on node californium.wikimedia.org

This was introduced with 4b4ea79b99ea8bcabad5578d472e93f4182f2358

Change-Id: I79f09eba780e0e64525fe73b3f91d60e76ecce55