wmflib: nuyaml_backend.rb handle empty files
Especially useful for scope testing using hiera_lookup right
now if you have labvirt1001.yaml and hosts/labvirt1001.yaml this
will raise an exception instead of looking further down the scope
path.

    nuyaml_backend.rb:166:in `block in lookup':
    undefined method `empty?' for nil:NilClass (NoMethodError)

Change-Id: If28b554fcf87d9bdcd25393a7cd98e3b34a25af9
tldr: ruby returns a nil object not an empty string here it seems