ldap: split client.pp into one file per class
Each class should be in a separate file. So i'm
removing the existing client.pp and put each class
into a separate file. No other changes to the classes.

This is the right structure and fixes these:

ERROR: ldap::client::pam not in autoload module layout on line 1
ERROR: ldap::client::nss not in autoload module layout on line 37
ERROR: ldap::client::utils not in autoload module layout on line 116
ERROR: ldap::client::sudo not in autoload module layout on line 245
ERROR: ldap::client::openldap not in autoload module layout on line 256
ERROR: ldap::client::includes not in autoload module layout on line 269

Change-Id: I01bfae251fff687fce1efcbbb94794be9bf863b2