Consolidate python-redis package declarations in ::redis::client::python
Different software stacks declared in operations/puppet require python-redis,
so let's consolidate the package declaration in a standalone, unparametrized
class that can be included unproblematically from anywhere it is needed.

Fixes Puppet on silver, broken by change Ib487dd5d4:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER:
Duplicate declaration: Package[python-redis] is already declared in file
/etc/puppet/modules/trebuchet/manifests/packages.pp:14; cannot redeclare at
/etc/puppet/manifests/mobile.pp:79 on node silver.wikimedia.org
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Change-Id: I7f7a7d795a15f2e435c3a0364a5dab79e6bdcbd9