planet: only use plugindirs config setting on buster
On the new rawdog v3, getting:

NameError: name 'load_plugins' is not defined

when the "plugindirs" config line is set.

elif l[0] == "plugindirs":
    for dir in parse_list(l[1]):
        load_plugins(dir, self)

Things work without it but still needed on old version or _that_ breaks.

T348392#9361498

Bug: T348392
Change-Id: Ica20b60268fda592b6f70e1d1157cfa8ecc99dc0