librenms: ensure install_dir exists
When applying role on a new instance, currently seeing:

Error: Cannot create /srv/librenms/rrd; parent directory /srv/librenms does not exist

Ensure the install_dir exists.

The owner/group/mode emulates the existing situation on netmon1001
so that it is not changed.

Bug:T159756
Change-Id: Iacb49925ee9e797d73a8f5f5ffada0f5ecebc72d