Revert "wdqs: add recording rule for req success ratio"
This reverts commit e22aacfe694d98454862b47aaaaf9e664d345afc.

Reason for revert: broke puppet on thanos-fe1001 due to invalid rules:

Execution of '/usr/bin/thanos tools rules-check --rules /etc/thanos-rule/rules/recording_rules.yaml20230124-2750748-14y26l0' returned 1: level=info ts=2023-01-24T20:29:29.425155453Z caller=tools.go:53 msg=checking pattern=/etc/thanos-rule/rules/recording_rules.yaml20230124-2750748-14y26l0
level=info ts=2023-01-24T20:29:29.425273395Z caller=tools.go:63 msg=checking filename=/etc/thanos-rule/rules/recording_rules.yaml20230124-2750748-14y26l0
 level=error ts=2023-01-24T20:29:29.425769935Z caller=tools.go:75 result=FAILED
level=error ts=2023-01-24T20:29:29.425807847Z caller=tools.go:77 error="yaml: line 22: mapping values are not allowed in this context"

Change-Id: I0b71efa09a3cf46d4cab33ff9515e8b21ddd4200