sretest: Uninstall external_clouds_vendors
We have this on the puppetmasters now, so we don't need sretest for
testing -- and it's failing with
  ModuleNotFoundError: No module named 'conftool.extensions.reqconfig'
anyway.

Bug: T270391
Change-Id: Icaf447fcefd40a99cef306d87ed2b644cfb43885