Revert "Include base::puppet in profile::puppetmaster::pontoon"
This reverts commit c911c621f92e5779429b75b8de1c65546659ba04.

Breaks existing pontoon masters with duplicate declaration:

Error: Could not retrieve catalog from remote server: Error 500 on
SERVER: Server Error: Evaluation Error: Error while evaluating a
Resource Statement, Evaluation Error: Error while evaluating a Resource
Statement, Duplicate declaration: Class[Base::Puppet] is already
declared at (file: /etc/puppet/modules/profile/manifests/base/puppet.pp,
line: 14); cannot redeclare (file:
/etc/puppet/modules/profile/manifests/puppetmaster/pontoon.pp, line: 9)
(file: /etc/puppet/modules/profile/manifests/puppetmaster/pontoon.pp,
line: 9, column: 5) on node puppet-01.swift.eqiad1.wikimedia.cloud

Change-Id: I6373b12ae39bbc869f495ccc44fa62e90447b213