labsdb-replica.my.cnf: Set slave_type_conversions
When doing an ALTER table on hosts whose master is running ROW based
replication, and attempting to expand a column, replication can break
with:

Last_SQL_Error: Column 8 of table 'commonswiki.image' cannot be
converted from type 'varchar(32)' to type 'varbinary(100)'

To prevent this we are setting slave_type_conversion to ALL_NON_LOSSY
which would allow the transaction to go on.
The documentation states:
"This mode permits conversions that do not require truncation or other
special handling of the source value; that is, it permits conversions
where the target type has a wider range than the source type.

Setting this mode has no bearing on whether lossy conversions are
permitted; this is controlled with the ALL_LOSSY mode. If only
ALL_NON_LOSSY is set, but not ALL_LOSSY, then attempting a conversion
that would result in the loss of data (such as INT to TINYINT, or
CHAR(25) to VARCHAR(20)) causes the slave to stop with an error."

Bug: T73563
Change-Id: Ice8d8f82a25fffcc3dde74d657af98174cba129d