Revert "Deploy mobileapps using scap3"
fails on tin:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER:
can't convert nil into Hash at /etc/puppet/modules/scap/manifests/server.pp:68
on node tin.eqiad.wmnet

This reverts commit a9f061b957ff40a7b4497842d89b3a0bdc4a553c.

Change-Id: I2ec8c13fa7f226d82bb68bd3d2a6460826942b72