Revert "k8s::client: Allow for install of all kubectl versions"
Revert submission 1115778-T341984-puppet

Reason for revert: puppet fails with:
Error: Could not update: undefined method `strip' for nil:NilClass
Error: /Stage[main]/K8s::Client/K8s::Package[kubectl-1.31]/
Package[kubernetes-client131]/ensure: change from 'purged' to '>=1.31
 <1.32' failed: Could not update: undefined method `strip' for
nil:NilClass


Bug: T341984
Change-Id: I5c662df012fb45918b2a571fdb5e99c667bea072