varnish: Fix python3-nacl dependency order issue
Running puppet on cp6016 after merging
Icebff5efd5656ff31b3283c2bac6611c8b5a66f3 triggered
an error cause python3-nacl hasn't been installed yet:
Notice:
/Stage[main]/Profile::Cache::Varnish::Frontend::Text/Exec[/usr/local/sbin/varnish-dp-key-generator
/etc/varnish/dp.master.key /etc/varnish/dp.daily.key]/returns: Tracebac
k (most recent call last):
Notice:
/Stage[main]/Profile::Cache::Varnish::Frontend::Text/Exec[/usr/local/sbin/varnish-dp-key-generator
/etc/varnish/dp.master.key /etc/varnish/dp.daily.key]/returns:   File "
/usr/local/sbin/varnish-dp-key-generator", line 12, in <module>
Notice:
/Stage[main]/Profile::Cache::Varnish::Frontend::Text/Exec[/usr/local/sbin/varnish-dp-key-generator
/etc/varnish/dp.master.key /etc/varnish/dp.daily.key]/returns:     impo
rt nacl.encoding
Notice:
/Stage[main]/Profile::Cache::Varnish::Frontend::Text/Exec[/usr/local/sbin/varnish-dp-key-generator
/etc/varnish/dp.master.key /etc/varnish/dp.daily.key]/returns: ModuleNo
tFoundError: No module named 'nacl'
Error: '/usr/local/sbin/varnish-dp-key-generator
/etc/varnish/dp.master.key /etc/varnish/dp.daily.key' returned 1 instead
of one of [0]
Error:
/Stage[main]/Profile::Cache::Varnish::Frontend::Text/Exec[/usr/local/sbin/varnish-dp-key-generator
/etc/varnish/dp.master.key /etc/varnish/dp.daily.key]/returns: change fr
om 'notrun' to ['0'] failed: '/usr/local/sbin/varnish-dp-key-generator
/etc/varnish/dp.master.key /etc/varnish/dp.daily.key' returned 1 instead
of one of [0]
Notice:
/Stage[main]/Profile::Cache::Varnish::Frontend::Text/Package[libsodium-dev]/ensure:
created
Notice:
/Stage[main]/Profile::Cache::Varnish::Frontend::Text/Package[python3-nacl]/ensure:
created

Bug: T315676
Change-Id: I798c9c7647e184cfad4e6604c772fb07a755ea69