prometheus: fix notify prometheus-redis-exporter
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship:
File[/etc/default/prometheus-redis-exporter@6379] { notify =>
Service[prometheus-redis-exporter@6379] }, because Service[prometheus-redis-exporter@6379] doesn't
seem to be in the catalog

Bug: T148637
Change-Id: I236099a63d0b04aa62c7c16d1cc6df6db9f27abb