Enable /srv/mediawiki symlink on prod deploy servers
* Remove deploy1002/deploy2002 from the mediawiki installation targets list.
* On deploy1002/deploy2002, make /srv/mediawiki a symlink to /srv/mediawiki-staging

This arrangement has been previously tested in beta.

Deployment instructions:

* Merge this change.
* On deploy1002/deploy2002, mv /srv/mediawiki /srv/mediawiki.old
* Run puppet agent

* Test:
** Run this command:

   PHP='php -d auto_prepend_file=/srv/mediawiki/wmf-config/PhpAutoPrepend.php' \
   mwscript showJobs.php --wiki testwiki --profiler text

   It should complete successfully (just prints 0).  In particular it should NOT say

   Fatal error: Cannot declare class Wikimedia\MWConfig\ServiceConfig,
   because the name is already in use in
   /srv/mediawiki-staging/src/ServiceConfig.php on line 9

** Run 'scap sync-world testing T329857'

If something terrible happens, revert this change, merge, delete
/srv/mediawiki and mv /srv/mediawiki.old /srv/mediawiki.

Bug: T329857
Change-Id: I8096ca21ef53c24cdc67807bb1450802863f0d05