Bump fd ulimit for gitblit
It fails to start since yesterday and the logfile has plenty of these
exceptions:

    java.io.IOException: Too many open files
       at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
       at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
       at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
       at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
       at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
       at java.lang.Thread.run(Thread.java:745)

Change-Id: I7c3bf4dfd8d24a8e03d9fdbdd538bb2ee501a32c