phabricator: remove require for homedir from systemd::sysuser
follow-up to I5f8d660e10c37f4

intention is to fix dependency issues including:

Error: Found 1 dependency cycle:
(Exec[Refresh sysusers] => User[phd] => File[/var/run/phd]
=> Systemd::Sysuser[phd] => User[phd])

Bug: T280597
Change-Id: I120d9bd81694279280db7094956cba87df9186bf