Revert "cassandra: stop declaring service resource"
it doesn't play well with nrpe::monitor_systemd_unit_state:

Error: Failed to apply catalog: Could not find dependency Service[cassandra]
for Nrpe::Monitor_systemd_unit_state[cassandra] at
  /etc/puppet/modules/cassandra/manifests/instance.pp:224

Change-Id: I58997603a03f2fb76a1ad4a13307d700042adcfd
This reverts commit 2585d9cff1c295cff9246cb494bf7949a55c61fc.