Revert "Covert Polish listinfo template back to ISO 8859-2"
This reverts commit fec4f446f8db0c4fb49a88f9767def1c174de86a.

Error: /Stage[main]/Mailman::Webui/File[/etc/mailman/pl/listinfo.html]
/content: change from {md5}040559cef4dc791bc0c22826d854543d to 
{md5}fe5e30773451f3cce1b77e0a14476a42 
failed: invalid byte sequence in UTF-8

Notice: /Stage[main]/Mailman::Listserve/File[/etc/mailman/mm_cfg.py]: Dependency File[/etc/mailman/pl/listinfo.html] has failures: true
Warning: /Stage[main]/Mailman::Listserve/File[/etc/mailman/mm_cfg.py]: Skipping because of failed dependencies
Notice: /Stage[main]/Mailman::Listserve/Service[mailman]: Dependency File[/etc/mailman/pl/listinfo.html] has failures: true
Warning: /Stage[main]/Mailman::Listserve/Service[mailman]: Skipping because of failed dependencies
Notice: /Stage[main]/Mailman::Webui/File[/var/lib/mailman/templates]: Dependency File[/etc/mailman/pl/listinfo.html] has failures: true
Warning: /Stage[main]/Mailman::Webui/File[/var/lib/mailman/templates]: Skipping because of failed dependencies
Notice: Finished catalog run in 9.89 seconds

Change-Id: I65e95bb278686ec8abed814a30d68e2a80a689be