swift: correct handling of non-ASCII paths in rewrite.py & test suite
wmf/rewrite.py was failing on bullseye for objects with non-ASCII
paths. This is because Swift's "swob" implementation takes the WSGI
PATH_INFO, un-url-encodes it, and decodes the resulting byte string as
if it were latin1. This transformation is 8-bit clean and reversible,
but the "string" representation is mojibaked if the path was a byte
sequence in an incompatible encoding (limiting the operations that may
safely be carried out on it).

In fact, however, MW uses utf-8 for its swift paths; so we have to
take care when setting path_info that we set it as a byte
sequence (which swob may then latin1-decode internally before
latin1-encoding it back to a byte sequence later).

The test suite has been modified to test this behaviour with two new
paths containing non-ASCII characters.

Further, the test suite was failing because our purging policies have
changed, so attempting to purge was getting 403 (permission denied);
keep one purge test to check that the now-expected 403 is returned.

New test output on unpatched bullseye host:
```
mvernon@ms-fe1012:~$ python3 ./rewrite_integration_test.py
......
======================================================================
FAIL: test_remapping_originals (__main__.WMFRewriteTest) (name='france')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mvernon/./rewrite_integration_test.py", line 53, in test_remapping_originals
    self.assertEqual(r.status_code, 200)
AssertionError: 400 != 200

======================================================================
FAIL: test_remapping_originals (__main__.WMFRewriteTest) (name='france-with-extra-slash')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mvernon/./rewrite_integration_test.py", line 53, in test_remapping_originals
    self.assertEqual(r.status_code, 200)
AssertionError: 400 != 200

======================================================================
FAIL: test_remapping_originals (__main__.WMFRewriteTest) (name='ukraine')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mvernon/./rewrite_integration_test.py", line 53, in test_remapping_originals
    self.assertEqual(r.status_code, 200)
AssertionError: 500 != 200

----------------------------------------------------------------------
Ran 7 tests in 0.272s

FAILED (failures=3)
```

New test output with this patch applied by hand (puppet disabled):
```
mvernon@ms-fe1012:~$ python3 ./rewrite_integration_test.py
......
----------------------------------------------------------------------
Ran 7 tests in 0.307s

OK
```

Bug: T305942
Change-Id: Ia9a9701da1cdce6787fc3259c334fa2859835efb