Revert "ganeti: move role from manifests/ into the role module"
Getting:

Error: Could not retrieve catalog from remote server: Error 400 on
SERVER: Could not find class role::salt::minions for
ganeti1001.eqiad.wmnet on node ganeti1001.eqiad.wmnet

This reverts commit 589aa3cd609f455119b3924be07458a39a086c0c.

Change-Id: Id3999fd0d2f1e66c7dab48e0e3f54f761d36d0c2