testreduce: break dependency cycle between apt::pin and require_package
attempted fix for:

Error: Failed to apply catalog: Found 1 dependency cycle:
(File[/etc/apt/preferences.d/stretch_backports.pref] =>
Apt::Pin[stretch-backports] => Package[npm] => Class[Packages::Npm]
=> Class[Testreduce] => Apt::Pin[stretch-backports] =>
File[/etc/apt/preferences.d/stretch_backports.pref])

This is because require_package already requires everything.

Bug: T201366
Change-Id: Ia321d0cb9edf1a761cf8e216d14cef8be59a6020