graphite: archive-instances: import missing yaml python module
Otherwise, the script fails when dealing with yaml.

2017-08-02 13:00:01,867 Exception!
Traceback (most recent call last):
  File "/usr/local/bin/archive-instances", line 139, in <module>
    deleted_hosts = get_deleted_instances()
  File "/usr/local/bin/archive-instances", line 121, in get_deleted_instances
    projects = get_projects_list()
  File "/usr/local/bin/archive-instances", line 108, in get_projects_list
    session=get_keystone_session('observer'),
  File "/usr/local/bin/archive-instances", line 36, in get_keystone_session
    nova_observer = yaml.safe_load(n)
NameError: global name 'yaml' is not defined

Bug: T189871
Change-Id: I6d29ae6ae15d26f3eaf7a68b25028aa562ff867b
Signed-off-by: Arturo Borrero Gonzalez <aborrero@wikimedia.org>