Work around /etc/default/elasticsearch variable expansion issue
When logstash1004 (jessie host) was upgraded to Elasticsearch 1.6.0 the
service failed to start with the error message:

  Error: Could not find or load main class ${ES_JAVA_OPTS}

Adding `set -x` to /usr/share/elasticsearch/bin/elasticsearch showed
that the java command line constructed by that script and
/etc/init.d/elasticsearch contained this substring in the middle:

  -Dfile.encoding=UTF-8 ${ES_JAVA_OPTS} -XX:GCHeapFreeLimit=10

`-Dfile.encoding=UTF-8` is the end of $JAVA_OPTS. `${ES_JAVA_OPTS}
-XX:GCHeapFreeLimit=10` is the last line of $ES_JAVA_OPTS that we were
configuring in /etc/default/elasticsearch but in a strange state where
the variable expansion had not been performed when
/etc/init.d/elasticsearch sourced the defaults file.

Change-Id: If2fd861b0bbb345317c90f0ca08e3df4a9a20bcc