fix service group in kafka role to unbreak icinga
follow-up to Change-Id: I6ca7760392

there was a typo, an additional "<U+200B>" in there

hard to see, (even here in gerrit), but it broke icinga
config on neon, so puppet would not restart the service
anymore, and we could not apply any other changes


Error: Could not find any servicegroup matching '​analytics_eqiad'


Change-Id: I0969fe80e3c06c2b7c4ce7eb786febbd860819c7