contint: fix duplicate definition of imagemagick
as reported by Krinkle:

Error: Could not retrieve catalog from remote server:Error 400 on SERVER:
Duplicate declaration: Package[imagemagick] is already declared in file

/etc/puppet/modules/contint/manifests/packages.pp:92; cannot redeclare at
/etc/puppet/modules/mediawiki/manifests/packages.pp:13 on node
i-000004b1.eqiad.wmflabs

which kept him from provisioning any new instance

this got added I2e796443f88d11ce

add an "if ! defined" around it like it's already done with other packages
to avoid this problem

Change-Id: Ia3d002201734cd57bc3dc2a573dfd80897139122