Revert "nrpe: manage sudo rules via nrpe::check"
This reverts commit 5aa6e5d2b0dc3346779b69f4d479e60dfe985e56.

Reason for revert: 

Change-Id: Idfadd02dea42aae7f305af782c6a35984a04039b
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Nrpe::Check[check_tcpircbot]: parameter 'command' expects a String value, got Undef (file: /etc/puppet/modules/nrpe/manifests/monitor_service.pp, line: 55) on node alert1001.wikimedia.org