puppet_compiler: manage facts dir permissions
The puppet compiler fails with the following error if it does not have
permission to read the facts dir

ERROR: Unable to find facts for host

Bug: T236717
Change-Id: I5e6f6151be7d1beadfc962570bf7ec60503f5673