rsync: readd incoming and outgoing chmod
Previously rsync::server::module had support to set incoming and
outgoing chmod. That got removed, probably because we had no use for
those parameters at the time.

doc1001.eqiad.wmnet hosts doc.wikimedia.org and has files rsynced in
that belongs to user `doc-uploader`, the same tree also have files
deployed from git by regular users (members of `wikidev`).

Directories under /srv/docroot/org/wikimedia/doc might be changed by
rsync to no more be group owned which prevent users from updating them
via git:

    error: unable to unlink old 'org/wikimedia/doc/default.html': Permission denied
    fatal: Could not reset index file to revision 'origin/master'.

The manual fix:

    sudo -u doc-uploader chmod g+w /srv/docroot/org/wikimedia/doc

Bring back support for incoming_chmod and outgoing_chmod (from 09ae10ec7)
Add back tests for file chmods (from e587f9cab)

Default both to 'undef' in order to use whatever default is provided by
rsyncd.

d3c861bcaf already applies the parameters to doc1001.eqiad.wmnet (it got
merged first although it depended on this change).

Hosts: doc1001.eqiad.wmnet, install1002.wikimedia.org

Bug: T137890
Bug: T237707
Change-Id: I4998d91e88f6f8ec7fc13ea5f3442fd262aea782