Increase priority of php-mailparse
Needs to be loaded after other modules.

With priority 20:

`php -re mailparse`

```PHP Warning:  PHP Startup: Unable to load dynamic library 'mailparse.so'
 (tried: /usr/lib/php/20170718/mailparse.so (/usr/lib/php/20170718/mailparse.so:
 undefined symbol: mbfl_convert_filter_flush),
/usr/lib/php/20170718/mailparse.so.so (/usr/lib/php/20170718/mailparse.so.so: cannot open shared
 object file: No such file or directory)) in Unknown on line 0
Exception: Extension mailparse does not exist
```

With priority=21:

`php -re mailparse`

```Extension [ <persistent> extension #43 mailparse version 3.0.2 ] {
...
```

Bug: T224752
Change-Id: Ie1eccb5c24dbe532143c387f36a666a27a747d36