P::mediawiki::mcrouter_wancache: add shad data for cloud proxies
Currently deployment prep puppet is failinf with

  Error: Could not retrieve catalog from remote server: Error 500 on SERVER:
    Server Error: Evaluation Error: Error while evaluating a Resource Statement,
    Evaluation Error: Error while evaluating a Method call, 'map' expects one of:
  (Hash hash, Callable[2, 2] block)
    rejected: parameter 'hash' expects a Hash value, got Undef
  (Hash hash, Callable[1, 1] block)
    rejected: parameter 'hash' expects a Hash value, got Undef
  (Iterable enumerable, Callable[2, 2] block)
    rejected: parameter 'enumerable' expects an Iterable value, got Undef
  (Iterable enumerable, Callable[1, 1] block)
    rejected: parameter 'enumerable' expects an Iterable value, got Undef
    (file: /etc/puppet/modules/mediawiki/manifests/mcrouter/yaml_defs.pp, line: 23, column: 47)
   on node deployment-deploy01.deployment-prep.eqiad.wmflabs

This CR adds an empty proxy entry for cloud hosts

Change-Id: I477744be7dbd14ff9daf8000c6c45bb7baca4755