maps: move roles to modules/role/
ERROR: role::maps not in autoload module layout on line 4
ERROR: role::maps::master not in autoload module layout on line 45
ERROR: role::maps::slave not in autoload module layout on line 90

Moved "role::maps" to "role::maps::server", BUT it seems like
only maps::master and maps::slave are used?

Change-Id: I2a44ee9c026d4290b932d8ccac15410fb6d4b00e