librenms: ensure install_dir exists, add it as required resource
When applying role on a new instance, currently seeing:

Error: Cannot create /srv/librenms/rrd; parent directory /srv/librenms does not exist

Ensure the install_dir exists, add it as a required resource
for config and rrd dir.

Change-Id: Iacb49925ee9e797d73a8f5f5ffada0f5ecebc72d