performance::site: require libapache2-mod-uwsgi
follow-up to I0677c2c610a6897e which uses mod uwsgi

The httpd class doesn't automatically require the
package so when puppet tried to run a2enmod it failed.

ERROR: Module uwsgi does not exist!

Bug: T159354
Change-Id: I56e214b7eb8b50a6ccebed985783edeb10ec6a0b