logrotate require archive dir to be created!
logrotate apparently does not create the archive directory when rotating
files, which lead to file not being rotated!

 # logrotate -d -v /etc/logrotate.d/mw-udp2log
 reading config file /etc/logrotate.d/mw-udp2log
 reading config info for /home/wikipedia/logs/*.log
 olddir is now /home/wikipedia/logs/archive
 error: /etc/logrotate.d/mw-udp2log:17 error verifying olddir path
 /home/wikipedia/logs/archive: No such file or directory
 removing last 1 log configs
 #

So we need to have puppet to explicitly create /h/w/logs/archive

Change-Id: Ic835a69e00c4dcd5d759c2d86d922e804e10c7cd