statsite: don't enable service when statsite is absent
Otherwise results in Puppet failure:

Error: Could not enable statsite@8125: Error:
/Stage[main]/Profile::Statsite/Statsite::Instance[8125]/Service[statsite@8125]/enable:
change from 'false' to 'true' failed: Could not enable statsite@8125:

Change-Id: I74b3b72afcac2212d947a5559528eba3638de0fd