sslcert::trusted_ca: add explicit ordering for jks
If puppet creates the empty .jks first, the keytool exec
will fail due to:
java.lang.Exception: Keystore file exists, but is empty:
/etc/ssl/localcerts/trusted_root_ca.jks

Bug: T291905
Change-Id: I8d5d98608db6c6701a06d5834898e175c18ee3c0