htpasswd: update to make a bit closer to standard puppet style
On puppet7 we get the following error
   org.jruby.exceptions.LoadError: (LoadError) no such file to load -- apr1md5
I suspect this is because jruby has a different load path.  update to
move things in to the puppet_x folder and use require_relative which is
the more common standard and i believe the advice approach

Hosts: C:docker::registry::web
Hosts: C:icinga::web
Hosts: P:mediawiki::php::monitoring
Hosts: P:etcd::tlsproxy
Hosts: P:sretest
Hosts: P:icinga
Bug: T348272
Change-Id: I56ce39b6dd9fd2527375e080d5af5304b7db0254