Remove passwords::ldap::production from role::webperf::profiling_tools
Now included in profile::webperf::xhgui and causing

Error: Could not retrieve catalog from remote server: Error 500 on SERVER:
Server Error: Evaluation Error: Error while evaluating a Resource Statement,
Duplicate declaration: Class[Passwords::Ldap::Production] is already
declared; cannot redeclare at
/etc/puppet/modules/role/manifests/webperf/profiling_tools.pp:17 at
/etc/puppet/modules/role/manifests/webperf/profiling_tools.pp:17:5
on node webperf1002.eqiad.wmnet

Change-Id: If83805238a4684390a8dc93d4b7e57143567c41e