nodepool: use OpenStack modules from jessie-backports
Nodepool 0.1.0 requires python-novaclient >= 2.21.0 while Jessie
provides 2.18.1.
Pin python-novaclient to jessie-backports which has 2.23.0.

The OpenStack client utility needs to be backported as well or it emits
a warning and errors out:

  $ openstack server list
  /usr/lib/python2.7/dist-packages/novaclient/v1_1/__init__.py:30:
  UserWarning: Module novaclient.v1_1 is deprecated (taken as a basis
  for novaclient.v2). The preferable way to get client class or object
  you can find in novaclient.client module.
  warnings.warn("Module novaclient.v1_1 is deprecated (taken as a basis
  for "
  ERROR: openstack url_for() got an unexpected keyword argument
  'volume_service_name'
  $

Bug: T104971
Change-Id: I4a787185bdcb6b12566c85687b2139858c4dc04c