webperf: handle missing 'duration' in schema
stuck in a restart loop on hafnium:

```
Traceback (most recent call last):
  File "/srv/webperf/navtiming.py", line 116, in <module>
    f(meta)
  File "/srv/webperf/navtiming.py", line 61, in handle_save_timing
    duration = event['duration']
KeyError: u'duration'
```

Bug: T85909
Change-Id: If406cc3964fd8b5178619f1b3e9d6becd3b93ece