aptrepo: add thirdparty/ci component to bookworm-wikimedia
Follow-up to I8117401236047.

We added jenkins to the list of upgrade-able packages
but it references component thirdparty/ci which is not
in bookworm-wikimedia yet.

[apt1002:/srv/wikimedia] $  sudo -i reprepro -C thirdparty/ci
 --restrict=jenkins checkupdate bookworm-wikimedia

Error: distribution 'bookworm-wikimedia' uses flat update pattern 'jenkins'
with target component 'thirdparty/ci' which it does not contain!
There have been errors!

Bug: T392127
Change-Id: I35b69fd055e8e92ce67bbe4f9127f8fae89eee37