puppetmaster: fix puppetsigner on non salt master
On the integration labs project we auto sign the puppet certs on
integration-puppetmaster using puppetsigner.py . The script also manages
salt keys and yields:

root@integration-puppetmaster:~# /usr/local/sbin/puppetsigner.py
Traceback (most recent call last):
  File "/usr/local/sbin/puppetsigner.py", line 82, in <module>
    '--out', 'json'])
  File "/usr/lib/python2.7/subprocess.py", line 537, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

The reason is integration-puppetmaster has no salt installations and the
script fails when invoking salt-key.

Wrap the salt related code to only execute when /usr/bin/salt-key
exists which should be good enough to detect whether we are on the salt
master.

Bug: T102488
Change-Id: I23738233a575657770f15cc16b67b75636f0a517