smokeping: ensure dnsutils is installed, use require_package
smokeping did not run on netmon1002 because:

ERROR: /etc/smokeping/config.d/Probes, line 17: ERROR: DNS 'binary' does not point to an executable

line 17 is: binary = /usr/bin/dig

dig is missing because it gets only installed from package dnsutils, which isn't here
by default or from base, at least not now in stretch.

Ensure it is installed, also use require_package() to install all required
packages.

Bug: 159756
Change-Id: I2582bb73085b8f3991c065eb7017eacce02a5ec2