[wdqs] use an Integer instead of String for jmx_exporter port
Seems to cause a failure:

Could not retrieve catalog from remote server: Error 500 on SERVER: Server
Error: Evaluation Error: Error while evaluating a Resource Statement,
Profile::Prometheus::Jmx_exporter[wdqs-updater]: parameter 'port' expects a
Stdlib::Port = Integer[0, 65535] value, got String (file:
/etc/puppet/modules/profile/manifests/query_service/streaming_updater.pp, line:
18) on node wdqs1009.eqiad.wmnet

Change-Id: I2006848a9092075458ad9d4dd9bf5fdf36558f3c