opensearch: change pki algo to rsa
Why: Starting OpenSearch 2.7.0 with ecdsa certificates causes an
OpenSearchUncaughtExceptionHandler error tracing back to a
NoSuchMethodError from the BouncyCastle dependency.  This was not
observed when RSA certificates were used.

What: Change the cfssl keys for OpenSearch to RSA.

Bug: T350516
Change-Id: I5c3757371d9b7e1e19bbcdca5198c5a3c326c4a4