Revert "P:cumin::master: Use sudo to run the check command"
This reverts commit f5f0ed3247e69394a92cb3798a7b7de9eac4db95.

Reason for revert: Strange error which looks unrelated but revert to rule out

Change-Id: I910ad7bbb62b49501ecb4eaad9988a9adaa941ee
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Lookup of key 'profile::standard::has_default_mail_relay' failed: Unable to parse (/etc/puppet/private/hieradata/role/common/cluster/management.yaml): mapping values are not allowed in this context at line 3 column 17 (file: /etc/puppet/modules/role/manifests/cluster/management.pp, line: 12, column: 5) on node cumin1001.eqiad.wmnet