librenms: fix logrotate cronspam
error: skipping "/var/log/librenms/daily.log" because parent directory
has insecure permissions (It's world writable or writable by group which is not "root")
Set "su" directive in config file to tell logrotate which user/group
should be used for rotation.

Change-Id: I8bc73edf1a5f23b108efef6817584adbd3b7e2e9