Qualify erb template variables in puppet self.conf.erb
In cloud vps self hosted puppet, I am getting
  Detail: undefined local variable or method `ssldir' for
  #<Puppet::Parser::TemplateWrapper:0x007eff50a16d68>
  at /etc/puppet/modules/puppet/manifests/self/config.pp:92:20
  on node pp1.analytics.eqiad.wmflabs

I guess unqualified class variables are no longer supported! :)

Change-Id: I9c783fe77d50ea40a08bdd820fd229f55989cd69