helmfile: set HELM environment variables for the admin-ng systemd jobs
We do this because without these environment variables, the `helm diff` plugin
cannot be found, and the job fails with
```
err 0: command "/usr/bin/helm3" exited with non-zero status:
PATH:
  /usr/bin/helm3
ARGS:
  0: helm3 (5 bytes)
  1: diff (4 bytes)
  2: upgrade (7 bytes)
  3: --reset-values (14 bytes)
  4: --allow-unreleased (18 bytes)
  5: istio-gateways-networkpolicies (30 bytes)
  6: wmf-stable/raw (14 bytes)
  7: --namespace (11 bytes)
  8: istio-system (12 bytes)
  9: --values (8 bytes)
  10: /tmp/values268121303 (20 bytes)
  11: --detailed-exitcode (19 bytes)
  12: --kubeconfig=/etc/kubernetes/admin-dse-k8s-eqiad.config (55 bytes)
ERROR:
  exit status 1
EXIT STATUS
  1
STDERR:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
COMBINED OUTPUT:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.

```

Bug: T331894
Hosts: deploy2002.codfw.wmnet
Change-Id: I56d28fae2a29b2a149e6e04a2f55b087370be388