puppetmaster: fix puppetsigner early abort on non puppetmaster
On the integration labs project we auto sign the salt keys on
integration-saltmaster using puppet signer.py . Turns out the script
expects the instance to also be a puppetmaster. Thus when running puppet
cert list --all it yields:

    root@integration-saltmaster:~# /usr/local/sbin/puppetsigner.py
    Traceback (most recent call last):
      File "/usr/local/sbin/puppetsigner.py", line 43, in <module>
        if host[0] == "(":
    IndexError: list index out of range

That aborts the script early on preventing auto signing of salt keys.

Make the list of hosts empty when puppet cert list --all returns an
empty string.

Bug: T102487
Change-Id: I941e2aae8a77ff138971c22f2f932391ae21e5dc