deployment_server: Fix a type mismatch
This was introduced in Id547b3f9200d10c96f516b4fc1773f25c67cb1b4 just
now and fails to apply:

  Error: Failed to apply catalog: Parameter content failed on
  File[/etc/helmfile-defaults/services-eqiad.yaml]: Munging failed for value
  {"services"=>"---\nmathoid: [...] "} in class content: no implicit conversion
  of Hash into String

My oversight in the last code review, fixed here.

Bug: T378429
Change-Id: Ia7777bd31756417a8980781d89d1ed92e8a14226