add missing monitor_group pdf_eqiad
Error: Could not find any hostgroup matching 'pdf_eqiad'
(config file '/etc/icinga/puppet_hosts.cfg', starting on line 7880)

Change-Id: I0a9a71fad6440acd7afa52e72568323a7833f628