Removing lcarr from icinga contactgroups and permissions
icinga can't currently reload due to errors.  This should fix.

Error: Could not find any contact matching 'lcarr' (config file '/etc/icinga/contactgroups.cfg', starting on line 17)
Error: Could not expand member contacts specified in contactgroup (config file '/etc/icinga/contactgroups.cfg', starting on line 17)
   Error processing object config files!

Change-Id: Id3cee10fcfa6d79cbc525b7a5afbc192b5b21902