wmflib: add magru to sites
Currently causing puppet failures on prometheus hosts:

    Error: Could not retrieve catalog from remote server: Error 500 on
    SERVER: Server Error: Evaluation Error: Error while evaluating a
    Function Call, Class[Profile::Netbox::Data]:
    parameter 'prefixes' entry '10.140.0.0/24' entry 'site' expects a
    match for Wmflib::Sites = Enum['codfw', 'drmrs', 'eqdfw', 'eqiad',
    'eqord', 'eqsin', 'esams', 'ulsfo'], got 'magru'

Bug: T346722
Change-Id: I32f95287e495f0df65a0cd304aa3b01426535756