P:varnish::common: Add support for passing wikimedia_domains
We have some VCL that work on a list of wikimedia domains.  This CR adds
that list to hiera so it can be shared among different rules

Original CR failed with the following

Message from VCC-compiler:
Regexp compilation error:

missing )

('/etc/varnish/wikimedia_misc-frontend.vcl' Line 223 Pos 37)
                if (req.http.Host ~ "((^|\.)(wikipedia\.org|
wikimedia\.org|wikibooks\.org|wikinews\.org|wikiquote\.org|
wikisource\.org|wikiversity\.org|wikivoyage\.org|
wikidata\.org|wikimediafoundation\.org|wikiworkshop\.org|
wiktionary\.org|mediawiki\.org|wmfusercontent\.org|w\.wiki)$") {
------------------------------------############################

Running VCC-compiler failed, exited with 2
VCL compilation failed
Command failed with error code 106

Hosts: P:cache::base
Change-Id: Ic7991c6fc5f5f58cdd604863947b4d2eb16f9c30