hieradata: depool rhodium, bring back puppetmaster1002
Some puppet compilations have been failing with hiera-related errors, indeed the hiera is also
upgraded in stretch. Remove rhodium from rotation as a precaution and put back puppetmaster1002.

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation
Error: Error while evaluating a Function Call, Could not find data item
profile::ganeti::ganeti01.svc.eqiad.wmnet::nodes in any Hiera data file and no default supplied at
/etc/puppet/modules/profile/manifests/ganeti.pp:4:21 on node ganeti1005.eqiad.wmnet

Bug: T184562
Change-Id: Ia77413eee1b2420bcff927bc61917733e47ce929