elasticsearch requires $plugins_dir to exist
Without this directory (which is the target of a link)
elasticsearch will do the following:

java.lang.IllegalStateException: Unable to access 'path.plugins'
(/srv/deployment/elasticsearch/plugins)

Change-Id: I669c474b3ab39653c545d34f02e8c411754b1e59