thanos: don't enable compact when not needed
Puppet fails otherwise:

Error: Could not enable thanos-compact: Error:
/Stage[main]/Thanos::Compact/Systemd::Service[thanos-compact]/Service[thanos-compact]/enable:
change from 'false' to 'true' failed: Could not enable thanos-compact:

Bug: T252186
Change-Id: I00b726678e83146d0e82368a0129e77fbbba6aef