phabricator: don't use systemd::sysuser on phab2002 for now
after Idb8dfdd89f7dd1b puppet run on phab2002 failed with:

Error: Found 1 dependency cycle:
(Exec[Refresh sysusers] => User[scap] => Exec[bootstrap-scap-target]
=> Class[Scap] => Scap::Target[phabricator/deployment]
=> Package[phabricator/deployment] => Class[Phabricator::Phd]
=> Systemd::Sysuser[phd] => File[/etc/sysusers.d/phd.conf]
=> Exec[Refresh sysusers])\n

The require was just added in I79479c024f344.

So, for now, don't use systemd::sysuser on the new phabricator
host to unbreak puppet.

But we can also use this host to test re-enabling it later.

Bug: T313360
Bug: T280597
Change-Id: I725ff2c36815a1327bec8f908b8b566fd79b8b6e