gerrit::proxy: fix link target for gerrit logo
On first puppet run on a new machine setting up gerrit::proxy:

Error: Could not evaluate:
Could not retrieve information from environment production
source(s) file:///var/lib/gerrit2/review_site/static/wikimedia-codereview-logo.cache.png

And looking at the code it seems obvious why.

A link should have a target parameter, not a source parameter.

Just like the other link above does.

It's not clear to me why we didn't notice it since 2016 since
this seems to come all the way back from Ideebea72ddbd8.

On gerrit1003 in production it's currently NOT a link, it's the same
file in 2 separate locations.

diff /var/www/wikimedia-codereview-logo.cache.png
/var/lib/gerrit2/review_site/static/wikimedia-codereview-logo.cache.png

shows they are the identical but 2 copies of the PNG file.

Bug: T372804
Change-Id: Ib7b427aec47c8e29c83f60e4329e51442a9af87a