Revert "releases: use secret() for gpg keyring"
fails to compile on bromine with

Error: Could not retrieve catalog from remote server: Error 400 on SERVER:
Files must be fully qualified at
/etc/puppet/modules/reprepro/manifests/init.pp:173 on node bromine.eqiad.wmnet
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

This reverts commit 2ac1435b5663b6d9895bc271fd6cb8a1ac997ec1.

Change-Id: I4319997c74edcc4f0897e4524705f93aa6e7ac9c