Revert "mediawiki: use native min/floor funcs rather than inline_template"
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: comparison of String with 98 failed at /etc/puppet/modules/mediawiki/manifests/web.pp:20 on node mw1041.eqiad.wmnet

This reverts commit 3f266c6bb089256c4286f3caae2ec4f06a061ee5.

Change-Id: I28ef70cfbbe6af3808b45fa611ad47c189ae79cf