Revert "Make (graphite|gdash).wm.o go through misc-eqiad-lb"
It turns out that all of the magic this patch tries to do
(renaming tests so they run on one box but report for another)
doesn't work, and trying to do it makes icinga sad.

For instance:

Error: Could not find any host matching 'graphite.wikimedia.org' (config file '/etc/icinga/puppet_services.cfg', starting on line 131098)

This reverts commit a87afea676375aba4f0ec28228e28df0502e5321.

Change-Id: I58b4fb3de75e357dbac9a89f1fb4cd84efbff545