wmcs: maintain-meta_p missing python-requests
```
$ sudo /usr/local/sbin/maintain-meta_p --all-databases --purge
Traceback (most recent call last):
  File "/usr/local/sbin/maintain-meta_p", line 25, in <module>
    import requests
ImportError: No module named requests
```

This package must have been installed as a side effect of something else
previously. Seems likely to have broken as a result of reimaging as
stretch.

Change-Id: I8e00605d0e41cc436fed5c2936ae16e11170d143