swift: wmf/rewrite.py py2->3 HTTPMessage changes
In py2, the HTTPMessage class came from httplib[0] and was implemented using
mimetools.Message[1].

In py3, the HTTPMessage class comes from http.client[2] and is
implemented using email.message.Message[3].

These objects do not have the same methods, resulting in backtraces in
the 404 handler (e.g. for thumbs that need generating) ending thus:

File "/usr/local/lib/python3.9/dist-packages/wmf/rewrite.py", line 117, in handle404
c_t = uinfo.gettype()#012AttributeError: 'HTTPMessage' object has no attribute 'gettype'

Update rewrite.py to use the new methods.

[0] https://docs.python.org/2.7/library/httplib.html#httplib.HTTPMessage
[1] https://docs.python.org/2.7/library/mimetools.html#mimetools.Message
[2] https://docs.python.org/3/library/http.client.html#httpmessage-objects
[3] https://docs.python.org/3/library/email.compat32-message.html#email.message.Message

Bug: T305942
Change-Id: I192fec2f05bf8b0b6fceb19d753a213671aaa0dd