hhvm: add missing " in hhvm.default.systemd.erb
This popped up as " /etc/init.d/hhvm: 10: /etc/default/hhvm: Syntax
error: Unterminated quoted string" on mw1201 (and others).

Change-Id: I0e14f3509c3ed5ac44adfbad101efc8abe553acb