contint: Fix stretch support in package_builder
Causing puppet to fail on stretch

Error: Could not retrieve catalog from remote server: Error 400 on SERVER:
OS debian == jessie required. at /etc/puppet/modules/contint/manifests/package_builder.pp:8 on node jenkins-slave-01.git.eqiad.wmflabs

Change-Id: I7d1f1e84017b7afad3e18bd74e2c03fc08c3f407