add missing misc_esams hostgroup to icinga
we recently added all servers to misc hostgroups
again. when i looked at icinga for an unrelated change
i noticed icinga could not restart anymore, the reason:

Error: Could not find any hostgroup matching 'misc_esams'

so adding that so that Icinga can reload config again

Change-Id: Icdb57157557928c5de02bd3c26e44605c098c706