package_builder: add python3-pbr (anycast-healthchecker build)
While building anycast-healthchecker, it fails due to missing
python3-pbr Build-Depends dependency.

    Build-Depends: debhelper (>= 9), dh-python, dh-systemd,
                   python3-all,
                   python3-setuptools,
                   python3-pbr

    ERROR: Could not find a version that satisfies the requirement pbr
    ERROR: No matching distribution found for pbr

Change-Id: I43d366ccebe73b5f2c56e1edecbf1f6f615faf05