labstore: move to require_package
Avoid puppet fail on double python3 declaration when used together with smart
module.

Error: Could not retrieve catalog from remote server: Error 500 on SERVER:
Server Error: Evaluation Error: Error while evaluating a Resource Statement,
Duplicate declaration: Package[python3] is already declared in file
/etc/puppet/modules/smart/manifests/init.pp:4; cannot redeclare at
/etc/puppet/modules/labstore/manifests/fileserver/exports.pp:5 at
/etc/puppet/modules/labstore/manifests/fileserver/exports.pp:5:5 on node
labstore1004.eqiad.wmnet

Change-Id: I44ddbc88f52e8621aa930b8921c995eb9f3bc1bd