Create /var/lib/atlas
The home_dir parameter of systemd::sysuser doesn't create the home directory,
it only sets that directory for the user.

Create it to fix Puppet errors when adding the config:

 Error: Cannot create /var/lib/atlas/.config; parent directory
        /var/lib/atlas does not exist
 Error: /[main]/Netops::Ripeatlas::Cli/File[/var/lib/atlas/.config]/ensure:
        change from 'absent' to 'directory' failed: Cannot create
	/var/lib/atlas/.config; parent directory /var/lib/atlas does not exist

Bug: T353419
Change-Id: I858d5309c1c43be2864bc37a384d9cd2724c44f6