kube-reload-certs: add "helm repo update"
The systemd timer seems broken again, due to the following error:

Error: Failed to render chart: exit status 1: Error: no cached repo
found. (try 'helm repo update'): open
/root/.cache/helm/repository/wmf-stable-index.yaml: no such file

Add "helm repo update" to force the update of the cache repo and
avoid spurious errors.

Change-Id: Ifd1edc27a2423e96903d5703b64e86eb48c0a0ab