Revert "x509-bundle.py: Port to Python 3"
This reverts commit 49eb5257f0de97e80616da274abd4e800f2fc880.

Reason for revert: Traceback (most recent call last):
  File "/usr/local/sbin/x509-bundle", line 140, in <module>
    main()
  File "/usr/local/sbin/x509-bundle", line 115, in main
    certpath = traverse_tree(args.cert, args.cadir)
  File "/usr/local/sbin/x509-bundle", line 89, in traverse_tree
    issuer = issuer_hash(cert)
  File "/usr/local/sbin/x509-bundle", line 75, in issuer_hash
    ], text=True).rstrip()
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'

Change-Id: I96ce73ff1a23e08e99c2a85a8d40f0f60f6265f2