deployment_server: Labs does not support ipv6 so we need to allow ipv6 to be an undef
I got this error

Change-Id: I96c8b39582724a0dd717dc3d96a3792b528372dc
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to parse inline template: address family must be specified at /etc/puppet/modules/interface/manifests/add_ip6_mapped.pp:24 on node phab-tin.phabricator.eqiad.wmflabs
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run