contint: Remove package libtemplate-perl from analytics.pp
This package is now in the base class so it is installed everywhere.

Which now causes

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Package[libtemplate-perl] is already declared; cannot redeclare at /etc/puppet/modules/contint/manifests/packages/analytics.pp:25 on node jenkins-slave-01.git.eqiad.wmflabs
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Change-Id: I4debb1f0fddcb2e7a55b0f36024cb93b897bbad3