remove breaking comma from swift monitor
follow-up to Change-Id: I4e1c263951060

the comma actually breaks Icinga.. :p

Error: Could not find a service matching host name
'ms-be3004' and description 'very high load average'...

Error: Could not expand member services specified in servicegroup ...
Error processing object config files!

RT: 8249
Change-Id: Ic89dcee033a313b2455e5636892b93016ac66e45