mariadb: Fix check_private_data.py after pymysql upgrade to 1.0.2
With the new version, pymysql is throwing a different error object:
pymysql.err.OperationalError: (1054, "Unknown column 'user_options' in 'where clause'")

And that is breaking the check of private data script

Change-Id: I01ef8bdb5ed3007594233cf512a82d16819b6e36