openstack: pass version hiera key down to nova conductor service class
The base class gained a new parameter (version) but all callers were not
accordingly updated, thus causing puppet catalog errors:

aborrero@labcontrol1001:~ 1 $ sudo puppet agent -t -v
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server:
 Error 500 on SERVER:
  Server Error:
   Evaluation Error:
    Error while evaluating a Function Call,
     Could not find data item profile::openstack::base::version in any Hiera
     data file and no default supplied at
     [.]modules/profile/manifests/openstack/base/nova/conductor/service.pp:2:16
     on node labcontrol1001.wikimedia.org

Change-Id: I0e84cfbf2168c80f6e17e7c48dd41a22a9128ccf
Signed-off-by: Arturo Borrero Gonzalez <aborrero@wikimedia.org>