puppetdb: create dbs before grants
I have run into this problem while bootstrapping a new puppetdb:

Notice: /Stage[main]/Profile::Puppetdb::Database/Postgresql::User[puppetdb_ro@puppetdb2002-ipv4]/
  Postgresql::Db_grant[grant access to puppetdb_ro@puppetdb2002-ipv4 on puppetdb]/
  Exec[db_grant: exec table grants grant access to puppetdb_ro@puppetdb2002-ipv4 on puppetdb]/
  returns: could not change directory to "/root": Permission denied

Notice: /Stage[main]/Profile::Puppetdb::Database/Postgresql::User[puppetdb_ro@puppetdb2002-ipv4]/
  Postgresql::Db_grant[grant access to puppetdb_ro@puppetdb2002-ipv4 on puppetdb]/
  Exec[db_grant: exec table grants grant access to puppetdb_ro@puppetdb2002-ipv4 on puppetdb]/
  returns: psql: FATAL:  database "puppetdb" does not exist

Error: '/usr/bin/psql --tuples-only --no-align  -c 'GRANT SELECT ON ALL TABLES IN SCHEMA "public"
  TO puppetdb_ro' puppetdb' returned 2 instead of one of [0]

Error: /Stage[main]/Profile::Puppetdb::Database/Postgresql::User[puppetdb_ro@puppetdb2002-ipv4]/
  Postgresql::Db_grant[grant access to puppetdb_ro@puppetdb2002-ipv4 on puppetdb]/
  Exec[db_grant: exec table grants grant access to puppetdb_ro@puppetdb2002-ipv4 on puppetdb]/
  returns: change from 'notrun' to ['0'] failed: '/usr/bin/psql --tuples-only --no-align  -c
  'GRANT SELECT ON ALL TABLES IN SCHEMA "public" TO puppetdb_ro' puppetdb'
  returned 2 instead of one of [0] (corrective)

Bug: T296550
Change-Id: I5679b197d7d69490b947868f9963f9d1d0d28c9d