gerrit: ensure symlink /etc/default/gerritcodereview
When applying the prod role on labs, with the latest
deb package as well as the older one, puppet said
it could not start the service because:

ERROR: GERRIT_SITE not set

Looking at /etc/init.d/gerrit we found:

"Configuration variables.  These may be set in /etc/default/gerritcodereview."

Looking at production we saw we 2 files /etc/default/gerritcodereview
and /etc/default/gerrit. They both have the same content, just 2 lines,
one of them setting the GERRIT_SITE.

GERRIT_SITE="/var/lib/gerrit2/review_site"
GERRIT_WAR="/var/lib/gerrit2/review_site/bin/gerrit.war"

But on labs, we did not get this file automatically.
Looking at the package, dpkg -L shows it installs /etc/default/gerrit
but not the other missing one.

So we just created it as a symlink to the existing file and this
is puppetizing it.

Bug: T141803
Change-Id: I2fec1de95dc1d96470466662c8b5747f77e5454e