apache: skip ganglia when it is unwanted
On CI slaves, we are using apache::site to create a virtual host. That
in turns invoke:

  apache::init
  apache::monitoring
  ganglia

But on labs ganglia is not installed via a hiera switch apparently. That
causes puppet to fail with:

Notice: Ganglia::Monitor::Packages/File[/etc/ganglia/conf.d]/ensure: created
Error: Cannot create /usr/lib/ganglia/python_modules;
       parent directory /usr/lib/ganglia does not exist

In apache::monitoring, skip ganglia installation entirely whenever hiera
indicates: $::standard::has_ganglia = False.

Bug: T134808
Change-Id: I8af072005de3fe750a227861722a9411dc45eb7f